os: linux
dist: xenial

language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

cache: npm

node_js:
  - 11
  - 10

install:
  - npm install

script:
  - npm test

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
    condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
